# .travis.yml

stages:
  - build

jobs:
  include:
    - stage: build
      name: "Build dev expo"
      if: branch = dev
      node_js:
        - '9.3'
      script:
        - cd pi2app
        - yarn add expo-cli
        - yarn expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - yarn build:android --non-interactive

    - stage: build
      name: "Build master expo"
      if: branch = master
      node_js:
        - '9.3'
      script:
        - cd pi2app
        - yarn add expo-cli
        - yarn expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - yarn build:android --non-interactive
