version: '3'
services:
  app:
    build: .
    ports:
      - 19000:19000
      - 19001:19001
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/pi2app
    command: bash -c "yarn install && yarn start"
    network_mode: "host"
